name: Logic-build-workflow
on:
  push:
    branches:
      - main
jobs:
  jobA:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.get-build-number.outputs.build-number }}
    steps:
    - name: Get build number
      id: get-build-number
      run: echo "::set-output name=build-number::42"

  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    if: ${{ failure() }}
    steps:
      - name: Show the variable values
        env:
          VAR1: This is
          VAR2: A Demo of
          VAR3: GitHub Actions
          VAR4: Workflow jobs
        run: |
          echo $VAR1 $VAR2 $VAR3 $VAR4.
  jobC:
    runs-on: ubuntu-latest
    needs: [jobA, jobB]
    if: ${{ needs.jobA.result == 'failure' || needs.jobB.result == 'failure' }}
    steps:
    - name: Rollback to print build number of JobA
      run: echo "Build number is ${{ jobs.jobA.outputs.build-number }}"