name: Logic-build-workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.get-build-number.outputs.build-number }}
    steps:
    - name: Get build number
      id: get-build-number
      run: echo "::set-output name=build-number::42"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Fail the test job
      run: |
        #!/bin/bash
        echo "This test always fails"
        exit 1

        
  rollback:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'failure' }}
    steps:
    - name: Rollback to print build number of build job
      run: echo "Build number is ${{ needs.build.outputs.build-number }}"
