name: Logic-build-workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.get-build-number.outputs.build-number }}
    steps:
    - name: Get build number
      id: get-build-number
      run: echo "::set-output name=build-number::42"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Fail the test job
      run: exit 1    
    - name: Show the variable values
      env:
        VAR1: This is
        VAR2: A Demo of
        VAR3: GitHub Actions
        VAR4: Workflow jobs
      run: |
        echo $VAR1 $VAR2 $VAR3 $VAR4
        
  rollback:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: ${{ needs.build.result == 'failure' && needs.test.result == 'failure' }}
    steps:
    - name: Rollback to print build number of build job
      run: echo "Build number is ${{ needs.build.outputs.build-number }}"
